### ISSUE TITLE
additional info in docs

### ISSUE THREAD

**Issue by niklaz** [Light-it-labs/laravel-linkedin-share#2]
Hi, 

great quick solution for v2! 

I guess there should be added in docs to add provider in list of providers in app.php configuration as well as alias for facade, 

``` 
'providers' => [ ... 
Lightit\LinkedinShare\LinkedinShareServiceProvider::class,
],
'aliases'=> [
'LinkedinShare'  => Lightit\LinkedinShare\Facades\LinkedinShare::class,
]
```

And to create linkedinshare configuration file with data for redirect_uri, client_id and client_secret: 

```
return [
	'redirect_uri' => '',
	'client_id' => '',
	'client_secret' =>'',
];
```

**Comment by alanbrande** [comment]
Hey niklaz,

Thanks for your suggestion. It is true that this package should be added to providers and aliases in versions of Laravel lower than 5.5.

Also I forgot to mention in the README that with vendor:publish the configuration file will be automatically created.

I will add it to the README.

Cheers,

Alan

**Comment by niklaz** [comment]
Hi Alan, 

Thank you!
