### ISSUE TITLE
using access_token instead of code for sharing

### ISSUE THREAD

**Issue by niklaz** [Light-it-labs/laravel-linkedin-share#3]
I apologize for being boring xD 
Just another suggestion.  
For sharing methods, there should be used access_token instead of short lived code. 
Code retrieved from authorization callback url, lives for LinkedIn only 20 seconds, giving it impossible to use it to retrieve access_token on each call. 
It would throw 400 error.

**Comment by alanbrande** [comment]
This packages uses the short lived code only to get the access_token, and uses the token for every other API request. Usually, you would get the short code in your front-end, using Oauth2 and provide it to the back-end to handle the rest.
Maybe we can extend this package to also allow shares receiving the access_token directly, to make it suitable for other use cases.

**Comment by niklaz** [comment]
Maybe providing it as additional argument, or providing type of code? I.E..: 

```
public function shareImage($code, $image, $text, $type = 'code') //$ype can be 'code' or 'access_token' 
{
        $client = new Client();
        
        $access_token = ($type === 'code') ? $this->getAccessToken($code) : $code;
        $personURN = $this->getProfile($access_token)['id'];
        .... 

} 
```

**Comment by alanbrande** [comment]
Looks good! Would you like to make a pull request?

**Comment by niklaz** [comment]
Thank you. I will make a pull request, just to fork the project.
