### ISSUE TITLE
Image sharing issue

### ISSUE THREAD

**Issue by muralianusha** [Light-it-labs/laravel-linkedin-share#7]
public function callback(Request $request){
       $code= $request->get('code'); 
       $text="Murali Sending url for link";
       $image = $_SERVER['DOCUMENT_ROOT'].'/47124254_1973608329422637_4904926392325505024_n.jpg';
       $accss_token=LinkedinShare::getAccessToken($code);
       LinkedinShare::shareImage($code,$image,$text,$accss_token);
      return 'done';
    }

Above code with artical sharing working well by LinkedinShare::shareArticle($code, $url, $text,$accss_token); (And notifications appeared in linked in)
Wen coming to image sharing code execution going well but image sharing notification not getting in linked in.
Please help me

**Comment by alanbrande** [comment]
It usually takes longer for image notifications to appear when you share images.
